// Code generated by "stringer -type Kind ."; DO NOT EDIT.

package p9p

import "fmt"

const _Kind_name = "KTversionKRversionKTauthKRauthKTattachKRattachKTerrorKRerrorKTflushKRflushKTwalkKRwalkKTopenKRopenKTcreateKRcreateKTreadKRreadKTwriteKRwriteKTclunkKRclunkKTremoveKRremoveKTstatKRstatKTwstatKRwstat"

var _Kind_index = [...]uint8{0, 9, 18, 24, 30, 38, 46, 53, 60, 67, 74, 80, 86, 92, 98, 106, 114, 120, 126, 133, 140, 147, 154, 162, 170, 176, 182, 189, 196}

func (i Kind) String() string {
	i -= 100
	if i >= Kind(len(_Kind_index)-1) {
		return fmt.Sprintf("Kind(%d)", i+100)
	}
	return _Kind_name[_Kind_index[i]:_Kind_index[i+1]]
}
