// Code generated by "stringer -type Kind"; DO NOT EDIT.

package p9p

import "fmt"

const _Kind_name = "KTversionKRversionKRauthKRattachKRerrorKRflushKRwalkKRopenKRcreateKRreadKRwriteKRclunkKRremoveKRstatKRwstat"

var _Kind_index = [...]uint8{0, 9, 18, 24, 32, 39, 46, 52, 58, 66, 72, 79, 86, 94, 100, 107}

func (i Kind) String() string {
	i -= 100
	if i >= Kind(len(_Kind_index)-1) {
		return fmt.Sprintf("Kind(%d)", i+100)
	}
	return _Kind_name[_Kind_index[i]:_Kind_index[i+1]]
}
